import 'package:flutter/widgets.dart';

import '../../shared/fonts/smart_home_devices_icons.dart';

const List<IconData> devicesIconsList = [
  SmartHomeDevicesIcons.airconditioner,
  SmartHomeDevicesIcons.alarm,
  SmartHomeDevicesIcons.booking,
  SmartHomeDevicesIcons.calculator,
  SmartHomeDevicesIcons.cctv,
  SmartHomeDevicesIcons.cctv_wifi,
  SmartHomeDevicesIcons.cloud,
  SmartHomeDevicesIcons.cpu,
  SmartHomeDevicesIcons.curtain,
  SmartHomeDevicesIcons.coffeemachine,
  SmartHomeDevicesIcons.door,
  SmartHomeDevicesIcons.door_wifi,
  SmartHomeDevicesIcons.electricity,
  SmartHomeDevicesIcons.emergency,
  SmartHomeDevicesIcons.fan,
  SmartHomeDevicesIcons.home,
  SmartHomeDevicesIcons.garage,
  SmartHomeDevicesIcons.home_sinal,
  SmartHomeDevicesIcons.insurance,
  SmartHomeDevicesIcons.kettle,
  SmartHomeDevicesIcons.laptop,
  SmartHomeDevicesIcons.laundry,
  SmartHomeDevicesIcons.lightning,
  SmartHomeDevicesIcons.microphone,
  SmartHomeDevicesIcons.microwave,
  SmartHomeDevicesIcons.motionsensor,
  SmartHomeDevicesIcons.music,
  SmartHomeDevicesIcons.outlet,
  SmartHomeDevicesIcons.oven,
  SmartHomeDevicesIcons.power,
  SmartHomeDevicesIcons.power_energy,
  SmartHomeDevicesIcons.refrigerator,
  SmartHomeDevicesIcons.router,
  SmartHomeDevicesIcons.remotecontrol,
  SmartHomeDevicesIcons.safebox,
  SmartHomeDevicesIcons.settings,
  SmartHomeDevicesIcons.smarthome,
  SmartHomeDevicesIcons.smartphone_control,
  SmartHomeDevicesIcons.smartphone_light,
  SmartHomeDevicesIcons.smartphone_lock,
  SmartHomeDevicesIcons.smartwatch,
  SmartHomeDevicesIcons.smokedetector,
  SmartHomeDevicesIcons.solarpanel,
  SmartHomeDevicesIcons.sprinkler,
  SmartHomeDevicesIcons.tap,
  SmartHomeDevicesIcons.temperature,
  SmartHomeDevicesIcons.temperature_cold,
  SmartHomeDevicesIcons.virtualreality,
  SmartHomeDevicesIcons.watering,
  SmartHomeDevicesIcons.webcam,
];
