import 'package:flutter/widgets.dart';

import '../../shared/fonts/smart_home_places_icons.dart';

const List<IconData> placesIconsList = [
  SmartHomePlacesIcons.house,
  SmartHomePlacesIcons.alarmclock,
  SmartHomePlacesIcons.aquarium,
  SmartHomePlacesIcons.armchair,
  SmartHomePlacesIcons.basin,
  SmartHomePlacesIcons.bathtub,
  SmartHomePlacesIcons.bed,
  SmartHomePlacesIcons.bookshelf,
  SmartHomePlacesIcons.cactus,
  SmartHomePlacesIcons.candles,
  SmartHomePlacesIcons.carpet,
  SmartHomePlacesIcons.clock,
  SmartHomePlacesIcons.cuckoo,
  SmartHomePlacesIcons.cushion,
  SmartHomePlacesIcons.desk,
  SmartHomePlacesIcons.desklamp,
  SmartHomePlacesIcons.desk_light,
  SmartHomePlacesIcons.door,
  SmartHomePlacesIcons.doorhandle,
  SmartHomePlacesIcons.drawer,
  SmartHomePlacesIcons.dresser,
  SmartHomePlacesIcons.fence,
  SmartHomePlacesIcons.fireplace,
  SmartHomePlacesIcons.floorlamp,
  SmartHomePlacesIcons.flowers,
  SmartHomePlacesIcons.globe,
  SmartHomePlacesIcons.hanger,
  SmartHomePlacesIcons.homecinema,
  SmartHomePlacesIcons.hourglass,
  SmartHomePlacesIcons.house,
  SmartHomePlacesIcons.lamp,
  SmartHomePlacesIcons.light,
  SmartHomePlacesIcons.lights,
  SmartHomePlacesIcons.livingroom,
  SmartHomePlacesIcons.mirror,
  SmartHomePlacesIcons.outlet,
  SmartHomePlacesIcons.painting,
  SmartHomePlacesIcons.plant,
  SmartHomePlacesIcons.refrigerator,
  SmartHomePlacesIcons.shower,
  SmartHomePlacesIcons.sofa,
  SmartHomePlacesIcons.stairs,
  SmartHomePlacesIcons.table,
  SmartHomePlacesIcons.toilet,
  SmartHomePlacesIcons.towel,
  SmartHomePlacesIcons.tv,
  SmartHomePlacesIcons.vase,
  SmartHomePlacesIcons.wallclock,
  SmartHomePlacesIcons.wallpaper,
  SmartHomePlacesIcons.wardrobe,
  SmartHomePlacesIcons.window,
];
